local sub_theme = User_vars.sub_theme

-- INFO: My idea is to list out the full colors in each colorscheme,
-- then come up with a list of all the semantic ways I'd use them,
-- then assign them in the final colorscheme.
local catppuccin = {
  latte = {
    Rosewater	= "#dc8a78",
    Flamingo	= "#dd7878",
    Pink	= "#ea76cb",
    Mauve	= "#8839ef",
    Red	= "#d20f39",
    Maroon	= "#e64553",
    Peach	= "#fe640b",
    Yellow	= "#df8e1d",
    Green	= "#40a02b",
    Teal	= "#179299",
    Sky	= "#04a5e5",
    Sapphire	= "#209fb5",
    Blue	= "#1e66f5",
    Lavender	= "#7287fd",
    Text	= "#4c4f69",
    Subtext1	= "#5c5f77",
    Subtext0	= "#6c6f85",
    Overlay2	= "#7c7f93",
    Overlay1	= "#8c8fa1",
    Overlay0	= "#9ca0b0",
    Surface2	= "#acb0be",
    Surface1	= "#bcc0cc",
    Surface0	= "#ccd0da",
    Base	= "#eff1f5",
    Mantle	= "#e6e9ef",
    Crust	= "#dce0e8",
  },
  macchiato = {
    Rosewater	= "#f4dbd6",
    Flamingo	= "#f0c6c6",
    Pink = "#f5bde6",
    Mauve	= "#c6a0f6",
    Red	= "#ed8796",
    Maroon	= "#ee99a0",
    Peach	= "#f5a97f",
    Yellow	= "#eed49f",
    Green	= "#a6da95",
    Teal	= "#8bd5ca",
    Sky	= "#91d7e3",
    Sapphire	= "#7dc4e4",
    Blue	= "#8aadf4",
    Lavender	= "#b7bdf8",
    Text	= "#cad3f5",
    Subtext1	= "#b8c0e0",
    Subtext0	= "#a5adcb",
    Overlay2	= "#939ab7",
    Overlay1	= "#8087a2",
    Overlay0	= "#6e738d",
    Surface2	= "#5b6078",
    Surface1	= "#494d64",
    Surface0	= "#363a4f",
    Base	= "#24273a",
    Mantle	= "#1e2030",
    Crust	= "#181926",
  },
}

return {
  bg = catppuccin[sub_theme].Base,
  fg = catppuccin[sub_theme].Text,
  pane = catppuccin[sub_theme].Crust,
  pane_2 = catppuccin[sub_theme].Mantle,
  surface = catppuccin[sub_theme].Surface0,
  surface_2 = catppuccin[sub_theme].Surface1,
  surface_3 = catppuccin[sub_theme].Surface2,
  overlay = catppuccin[sub_theme].Overlay0,
  overlay_2 = catppuccin[sub_theme].Overlay1,
  overlay_3 = catppuccin[sub_theme].Overlay2,
  subtext = catppuccin[sub_theme].Subtext0,
  subtext_2 = catppuccin[sub_theme].Subtext1,
  subtle = catppuccin[sub_theme].Overlay1,
  link_url = catppuccin[sub_theme].Rosewater,
  success = catppuccin[sub_theme].Green,
  warning = catppuccin[sub_theme].Peach,
  error = catppuccin[sub_theme].Maroon,
  search_tags = catppuccin[sub_theme].Blue,
  selection_bg = catppuccin[sub_theme].Surface2,
  selection_text = catppuccin[sub_theme].Text,
  cursor = catppuccin[sub_theme].Rosewater,
  cursor_text = catppuccin[sub_theme].Crust,
  border_active = catppuccin[sub_theme].Lavender,
  border_inactive = catppuccin[sub_theme].Overlay0,
  border_bell = catppuccin[sub_theme].Yellow,
  color0 = catppuccin[sub_theme].Surface1,
  color1 = catppuccin[sub_theme].Red,
  color2 = catppuccin[sub_theme].Green,
  color3 = catppuccin[sub_theme].Yellow,
  color4 = catppuccin[sub_theme].Blue,
  color5 = catppuccin[sub_theme].Pink,
  color6 = catppuccin[sub_theme].Teal,
  color7 = catppuccin[sub_theme].Subtext1,
  color8 = catppuccin[sub_theme].Surface2,
  color9 = catppuccin[sub_theme].Red,
  color10 = catppuccin[sub_theme].Green,
  color11 = catppuccin[sub_theme].Yellow,
  color12 = catppuccin[sub_theme].Blue,
  color13 = catppuccin[sub_theme].Pink,
  color14 = catppuccin[sub_theme].Teal,
  color15 = catppuccin[sub_theme].Subtext0,
  color16 = catppuccin[sub_theme].Peach,
  color17 = catppuccin[sub_theme].Rosewater,
  mark_1 = catppuccin[sub_theme].Lavender,
  mark_1_text = catppuccin[sub_theme].Crust,
  mark_2 = catppuccin[sub_theme].Mauve,
  mark_2_text = catppuccin[sub_theme].Crust,
  mark_3 = catppuccin[sub_theme].Sapphire,
  mark_3_text = catppuccin[sub_theme].Crust,
  hover = catppuccin[sub_theme].Sky,
  hover2 = catppuccin[sub_theme].Teal,
}

