local sub_theme = "dark"
--local sub_theme = User_vars.sub_theme or "dark"

local gruv = {
  light = {},
  dark = {
    bg = "#282828", -- bg(0) in palette
    fg = "#ebdbb2", -- fg(15) in palette
    grey1 = "#928374", -- gray in palette
    grey2 = "#3c3836", -- bg1 in palette
    red = "#cc241d", -- red(0) in palette
    soft_red = "#fb4934", -- red(9) in palette
    green = "#98971a", -- green(2) in palette
    soft_green = "#b8bb26", -- green(10) in palette
    yellow = "#d79921", -- yellow(3) in palette
    soft_yellow = "#fabd2f", -- yellow(11) in palette
    blue = "#458588", -- blue(4) in palette
    soft_blue = "#83a598", -- blue(12) in palette
    soft_blue2 = "#8ec07c", -- aqua(14) in palette
    purple = "#b16286", -- purple(5) in palette
    softpurple = "#d3869b", -- purplepurple(13) in palette
    aqua = "#689d6a", -- aqua(6) in palette
    white = "#ebdbb2", -- fg(15) in palette
    white2 = "#fbf1c7", -- fg0 in palette
    orange = "#d65d0e", -- orange in palette
    soft_orange = "#fe8019", -- orange in palette
  },
}
return {
  bg = gruv[sub_theme].bg,
  fg = gruv[sub_theme].fg,
  pane = gruv[sub_theme].grey1,
  pane_2 = gruv[sub_theme].grey2,
  surface = gruv[sub_theme].grey1,
  surface_2 = gruv[sub_theme].grey2,
  surface_3 = gruv[sub_theme].grey2,
  overlay = gruv[sub_theme].white,
  overlay_2 = gruv[sub_theme].white2,
  overlay_3 = gruv[sub_theme].grey1,
  subtext = gruv[sub_theme].white2,
  subtext_2 = gruv[sub_theme].white2,
  subtle = gruv[sub_theme].purple,
  link_url = gruv[sub_theme].orange,
  success = gruv[sub_theme].green,
  warning = gruv[sub_theme].yellow,
  error = gruv[sub_theme].red,
  search_tags = gruv[sub_theme].blue,
  selection_bg = gruv[sub_theme].grey1,
  selection_text = gruv[sub_theme].fg,
  cursor = gruv[sub_theme].soft_green,
  cursor_text = gruv[sub_theme].fg,
  border_active = gruv[sub_theme].orange,
  border_inactive = gruv[sub_theme].bg,
  border_bell = gruv[sub_theme].yellow,
  color0 = gruv[sub_theme].grey1,
  color1 = gruv[sub_theme].red,
  color2 = gruv[sub_theme].green,
  color3 = gruv[sub_theme].yellow,
  color4 = gruv[sub_theme].blue,
  color5 = gruv[sub_theme].purple,
  color6 = gruv[sub_theme].aqua,
  color7 = gruv[sub_theme].orange,
  color8 = gruv[sub_theme].white,
  color9 = gruv[sub_theme].soft_red,
  color10 = gruv[sub_theme].soft_green,
  color11 = gruv[sub_theme].soft_yellow,
  color12 = gruv[sub_theme].soft_blue,
  color13 = gruv[sub_theme].soft_purple,
  color14 = gruv[sub_theme].aqua,
  color15 = gruv[sub_theme].soft_orange,
  color16 = gruv[sub_theme].white2,
  color17 = gruv[sub_theme].grey1,
  mark_1 = gruv[sub_theme].green,
  mark_1_text = gruv[sub_theme].grey2,
  mark_2 = gruv[sub_theme].orange,
  mark_2_text = gruv[sub_theme].grey2,
  mark_3 = gruv[sub_theme].blue,
  mark_3_text = gruv[sub_theme].grey2,
  hover = gruv[sub_theme].soft_green,
  hover2 = gruv[sub_theme].aqua,
}
